project:
  type: website


execute:
  freeze: auto

website:
  title: "Terzijde"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/

brand: _brand.yml

theme: 
  - materia
  - brand
# theme:
#   light: 
#     - flatly
#     - brand
#   dark: 
#     - darkly
#     - brand


format:
  html:
    toc: true
    toc-depth: 4


