project:
  type: website


execute:
  freeze: auto

website:
  title: "Terzijde"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/

theme:
  light: 
    - sandstone
  dark: 
    - slate

brand: _brand.yml

format:
  html:
    toc: true
    toc-depth: 4


