project:
  type: website
execute:
  freeze: auto
website:
  title: "Terzijde"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: lux
    css: styles.css
    toc: false

  pdf:
    toc: false




